# Generated by Django 6.0.3 on 2026-03-25 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Poseidon Buffet Premium', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('hotline', models.CharField(default='1900 8888', max_length=20)),
                ('address', models.CharField(default='Tầng 4, Vincom Center, Hà Nội', max_length=500)),
                ('vat_tax', models.IntegerField(default=8)),
                ('service_charge', models.IntegerField(default=5)),
                ('open_time', models.TimeField(default='10:00')),
                ('close_time', models.TimeField(default='22:30')),
                ('bank_id', models.CharField(default='MB', max_length=50, verbose_name='Mã Ngân hàng (Ví dụ: MB, VCB)')),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số Tài khoản')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Chủ Tài Khoản')),
                ('ai_dataset_window', models.CharField(default='3_months', max_length=50)),
                ('ai_prediction_window', models.CharField(default='7_days', max_length=50)),
                ('ai_weather_sync', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuyenTruyCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('view_dashboard', models.BooleanField(default=False)),
                ('manage_pos', models.BooleanField(default=False)),
                ('manage_tables', models.BooleanField(default=False)),
                ('manage_menu', models.BooleanField(default=False)),
                ('manage_inventory', models.BooleanField(default=False)),
                ('manage_employees', models.BooleanField(default=False)),
                ('view_reports', models.BooleanField(default=False)),
                ('ai_analysis', models.BooleanField(default=False)),
                ('manage_settings', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quyen', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('info', 'Thông tin (Xanh/Đen)'), ('warning', 'Cảnh báo (Vàng)'), ('danger', 'Nguy hiểm (Đỏ)')], default='info', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
