# Generated by Django 5.2.10 on 2026-05-23 21:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restaurant_name', models.CharField(default='Poseidon Buffet Premium', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('hotline', models.CharField(default='1900 8888', max_length=20)),
                ('address', models.CharField(default='Tầng 4, Vincom Center, Hà Nội', max_length=500)),
                ('open_time', models.TimeField(default='10:00')),
                ('close_time', models.TimeField(default='22:30')),
                ('hold_table_time', models.IntegerField(default=15, verbose_name='Thời gian giữ bàn (Phút)')),
                ('vat_tax', models.IntegerField(default=8)),
                ('service_charge', models.IntegerField(default=5)),
                ('deposit_percent', models.IntegerField(default=20, verbose_name='Tỷ lệ cọc (%)')),
                ('bank_id', models.CharField(default='MB', max_length=50, verbose_name='Mã Ngân hàng')),
                ('bank_account_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số Tài khoản')),
                ('bank_account_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Tên Chủ Tài Khoản')),
                ('ai_dataset_window', models.CharField(default='3_months', max_length=50)),
                ('ai_prediction_window', models.CharField(default='7_days', max_length=50)),
                ('ai_weather_sync', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuyenTruyCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('table_view', models.BooleanField(default=False)),
                ('table_edit', models.BooleanField(default=False)),
                ('booking_view', models.BooleanField(default=False)),
                ('booking_edit', models.BooleanField(default=False)),
                ('booking_delete', models.BooleanField(default=False)),
                ('pos_view', models.BooleanField(default=False)),
                ('pos_edit', models.BooleanField(default=False, verbose_name='Quyền lên Order')),
                ('pos_checkout', models.BooleanField(default=False, verbose_name='Quyền Thanh toán')),
                ('menu_view', models.BooleanField(default=False)),
                ('menu_edit', models.BooleanField(default=False)),
                ('menu_delete', models.BooleanField(default=False)),
                ('inventory_view', models.BooleanField(default=False)),
                ('inventory_edit', models.BooleanField(default=False)),
                ('inventory_delete', models.BooleanField(default=False)),
                ('report_view', models.BooleanField(default=False)),
                ('system_all', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quyen', to='auth.group')),
            ],
        ),
        migrations.CreateModel(
            name='SystemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=255)),
                ('module', models.CharField(max_length=100)),
                ('level', models.CharField(choices=[('info', 'Thông tin (Xanh/Đen)'), ('warning', 'Cảnh báo (Vàng)'), ('danger', 'Nguy hiểm (Đỏ)')], default='info', max_length=20)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
