# Generated by Django 6.0.3 on 2026-03-29 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quyentruycap',
            name='ai_analysis',
        ),
        migrations.RemoveField(
            model_name='quyentruycap',
            name='manage_employees',
        ),
        migrations.RemoveField(
            model_name='quyentruycap',
            name='manage_inventory',
        ),
        migrations.RemoveField(
            model_name='quyentruycap',
            name='manage_menu',
        ),
        migrations.RemoveField(
            model_name='quyentruycap',
            name='manage_pos',
        ),
        migrations.RemoveField(
            model_name='quyentruycap',
            name='manage_settings',
        ),
        migrations.RemoveField(
            model_name='quyentruycap',
            name='manage_tables',
        ),
        migrations.RemoveField(
            model_name='quyentruycap',
            name='view_dashboard',
        ),
        migrations.RemoveField(
            model_name='quyentruycap',
            name='view_reports',
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='booking_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='booking_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='booking_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='inventory_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='inventory_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='inventory_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='pos_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='pos_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='report_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='system_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='deposit_percent',
            field=models.IntegerField(default=20, verbose_name='Tỷ lệ cọc (%)'),
        ),
        migrations.AddField(
            model_name='systemsetting',
            name='hold_table_time',
            field=models.IntegerField(default=15, verbose_name='Thời gian giữ bàn (Phút)'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='bank_id',
            field=models.CharField(default='MB', max_length=50, verbose_name='Mã Ngân hàng'),
        ),
    ]
