# Generated by Django 6.0.3 on 2026-03-29 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_quyentruycap_ai_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quyentruycap',
            name='pos_checkout',
            field=models.BooleanField(default=False, verbose_name='Quyền Thanh toán'),
        ),
        migrations.AlterField(
            model_name='quyentruycap',
            name='pos_edit',
            field=models.BooleanField(default=False, verbose_name='Quyền Lên đơn (Order)'),
        ),
    ]
