# Generated by Django 6.0.3 on 2026-03-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quyentruycap_pos_checkout_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quyentruycap',
            name='menu_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='menu_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='menu_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='table_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quyentruycap',
            name='table_view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quyentruycap',
            name='pos_edit',
            field=models.BooleanField(default=False, verbose_name='Quyền lên Order'),
        ),
    ]
