# Generated by Django 6.0.3 on 2026-03-25 15:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lam_viec', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày làm việc')),
                ('loai_ca', models.CharField(choices=[('morning', 'Ca Sáng (08:00 - 14:00)'), ('evening', 'Ca Tối (14:00 - 22:30)'), ('full', 'Full-time (Cả ngày)')], default='morning', max_length=20)),
                ('bo_phan', models.CharField(choices=[('kitchen', 'Bộ phận Bếp'), ('service', 'Phục vụ Sảnh'), ('cashier', 'Thu ngân / Lễ tân'), ('other', 'Khác')], default='service', max_length=20)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nv', models.CharField(max_length=20, unique=True)),
                ('ho_ten', models.CharField(max_length=255)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='Nam', max_length=10)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dia_chi', models.CharField(blank=True, max_length=500, null=True)),
                ('chuc_vu', models.CharField(max_length=100)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NgayNghi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_nghi', models.DateField(verbose_name='Ngày xin nghỉ')),
                ('ly_do', models.CharField(blank=True, max_length=255, null=True, verbose_name='Lý do nghỉ')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ngay_nghi', to='hrm.nhanvien')),
            ],
            options={
                'unique_together': {('nhan_vien', 'ngay_nghi')},
            },
        ),
        migrations.CreateModel(
            name='ChiTietCaLam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_lam_viec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_ca', to='hrm.calamviec')),
                ('nhan_vien', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrm.nhanvien')),
            ],
            options={
                'unique_together': {('ca_lam_viec', 'nhan_vien')},
            },
        ),
    ]
