# Generated by Django 5.2.10 on 2026-05-23 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NhanVien',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nv', models.CharField(max_length=20, unique=True)),
                ('ho_ten', models.CharField(max_length=255)),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], default='Nam', max_length=10)),
                ('ngay_sinh', models.DateField(blank=True, null=True)),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('dia_chi', models.CharField(blank=True, max_length=500, null=True)),
                ('chuc_vu', models.CharField(max_length=100)),
                ('anh_dai_dien', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CaLamViec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_lam_viec', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày làm việc/Xin nghỉ')),
                ('loai_ca', models.CharField(choices=[('morning', 'Ca Sáng'), ('evening', 'Ca Tối'), ('full', 'Full-time'), ('nghi_phep', 'Xin nghỉ')], default='morning', max_length=20)),
                ('bo_phan', models.CharField(choices=[('kitchen', 'Bếp'), ('service', 'Phục vụ'), ('cashier', 'Thu ngân'), ('other', 'Khác')], default='service', max_length=20)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
                ('nhan_vien', models.ManyToManyField(blank=True, related_name='ca_lam_viec', to='hrm.nhanvien')),
            ],
        ),
    ]
