# Generated by Django 6.0.3 on 2026-03-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chitietcalam',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ngaynghi',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='calamviec',
            name='bo_phan',
            field=models.CharField(choices=[('kitchen', 'Bếp'), ('service', 'Phục vụ'), ('cashier', 'Thu ngân'), ('other', 'Khác')], default='service', max_length=20),
        ),
        migrations.AlterField(
            model_name='calamviec',
            name='loai_ca',
            field=models.CharField(choices=[('morning', 'Ca Sáng'), ('evening', 'Ca Tối'), ('full', 'Full-time')], default='morning', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='chitietcalam',
            constraint=models.UniqueConstraint(fields=('ca_lam_viec', 'nhan_vien'), name='unique_nhan_vien_ca_lam'),
        ),
        migrations.AddConstraint(
            model_name='ngaynghi',
            constraint=models.UniqueConstraint(fields=('nhan_vien', 'ngay_nghi'), name='unique_ngay_nghi_nhan_vien'),
        ),
    ]
