# Generated by Django 6.0.3 on 2026-03-25 15:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIDuDoanLuuLuong',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_du_doan', models.DateField(verbose_name='Ngày')),
                ('ca_lam_viec', models.CharField(choices=[('sang', 'Ca Sáng (10h-15h)'), ('toi', 'Ca Tối (17h-22h)'), ('ca_ngay', 'Cả ngày')], max_length=20, verbose_name='Ca làm việc')),
                ('khach_thuc_te', models.IntegerField(blank=True, help_text='Bỏ trống nếu là ngày ở tương lai', null=True, verbose_name='Khách thực tế (Pax)')),
                ('ai_du_doan_khach', models.IntegerField(verbose_name='AI Dự đoán (Pax)')),
                ('ty_le_lap_day', models.FloatField(verbose_name='Tỷ lệ lấp đầy dự kiến (%)')),
                ('trang_thai', models.CharField(choices=[('vang', 'Vắng (<40%)'), ('binh_thuong', 'Bình thường (40-75%)'), ('dong', 'Đông (75-95%)'), ('qua_tai', 'Quá tải / Full (>95%)')], max_length=20, verbose_name='Trạng thái cảnh báo')),
                ('doanh_thu_ky_vong', models.IntegerField(verbose_name='Doanh thu kỳ vọng (VNĐ)')),
                ('loi_khuyen_van_hanh', models.TextField(verbose_name='Đề xuất vận hành (Nhân sự/Bàn ghế)')),
            ],
            options={
                'verbose_name': 'Dự đoán lượng khách',
                'verbose_name_plural': '4. AI Phân tích lưu lượng',
                'ordering': ['-ngay_du_doan'],
            },
        ),
        migrations.CreateModel(
            name='AIDuDoanTieuThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_du_doan', models.DateField(default=django.utils.timezone.now, verbose_name='Ngày dự đoán')),
                ('ten_mon', models.CharField(max_length=255, verbose_name='Tên món / Nguyên liệu')),
                ('nhom_mon', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nhóm món (Thịt/Hải sản/Tráng miệng)')),
                ('tieu_thu_ky_truoc', models.FloatField(verbose_name='Tiêu thụ kỳ trước (Kg/Phần)')),
                ('ai_du_doan_tieu_thu', models.FloatField(verbose_name='AI Dự đoán kỳ này (Kg/Phần)')),
                ('don_vi', models.CharField(default='Kg', max_length=20, verbose_name='Đơn vị tính')),
                ('bien_dong_phan_tram', models.FloatField(verbose_name='Biến động (%)')),
                ('xu_huong', models.CharField(choices=[('tang', 'Tăng đột biến'), ('giam', 'Giảm mạnh'), ('binh_thuong', 'Bình thường')], max_length=20, verbose_name='Xu hướng')),
                ('loi_khuyen_ai', models.TextField(verbose_name='Hành động đề xuất (Prep List Action)')),
            ],
            options={
                'verbose_name': 'Dự đoán nguyên liệu',
                'verbose_name_plural': '2. AI Dự đoán tiêu thụ',
                'ordering': ['-ngay_du_doan', '-bien_dong_phan_tram'],
            },
        ),
        migrations.CreateModel(
            name='AIEngineLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(choices=[('traffic', 'Dự đoán lượng khách'), ('inventory', 'Dự đoán tiêu thụ nguyên liệu'), ('menu', 'Tối ưu thực đơn (BCG Matrix)')], max_length=50, verbose_name='Phân hệ AI')),
                ('lan_chay_cuoi', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian phân tích')),
                ('do_chinh_xac', models.FloatField(help_text='Độ chính xác mô hình (%) - Confidence Score', verbose_name='Độ chính xác (%)')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Trạng thái hoạt động')),
            ],
            options={
                'verbose_name': 'Nhật ký AI',
                'verbose_name_plural': '1. Nhật ký hệ thống AI',
            },
        ),
        migrations.CreateModel(
            name='AIPhanTichThucDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thang_phan_tich', models.DateField(verbose_name='Tháng phân tích (Dữ liệu đầu tháng)')),
                ('ten_mon', models.CharField(max_length=255, verbose_name='Tên món ăn')),
                ('nhom_mon', models.CharField(max_length=100, verbose_name='Nhóm món')),
                ('ty_suat_loi_nhuan', models.FloatField(help_text='Trục Y (0-100)', verbose_name='Biên lợi nhuận (%)')),
                ('do_pho_bien', models.FloatField(help_text='Trục X (0-100)', verbose_name='Độ phổ biến (Lượt lấy)')),
                ('phan_loai_bcg', models.CharField(choices=[('star', 'Ngôi Sao (Stars)'), ('horse', 'Ngựa Cày (Plowhorses)'), ('puzzle', 'Câu Đố (Puzzles)'), ('dog', 'Chó Mực (Dogs)')], max_length=20, verbose_name='Phân loại ma trận')),
                ('food_cost', models.FloatField(verbose_name='Food Cost (%)')),
                ('ty_le_hao_hut', models.FloatField(verbose_name='Tỷ lệ hao hụt/bỏ đi (%)')),
                ('loi_khuyen_ai', models.TextField(verbose_name='Đề xuất hành động (Giữ/Bỏ/Tăng giá/Quảng bá)')),
            ],
            options={
                'verbose_name': 'Phân tích thực đơn',
                'verbose_name_plural': '3. AI Tối ưu thực đơn (BCG)',
                'ordering': ['-thang_phan_tich', 'phan_loai_bcg'],
            },
        ),
    ]
