# Generated by Django 5.2.10 on 2026-05-23 21:16

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NguyenLieu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nl', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã NL')),
                ('ten_nguyen_lieu', models.CharField(max_length=255, verbose_name='Tên Nguyên liệu')),
                ('danh_muc', models.CharField(choices=[('hai_san', 'Hải Sản Tươi Sống'), ('thit', 'Thịt (Bò, Gà, Heo)'), ('rau_cu', 'Rau Củ Quả'), ('gia_vi', 'Gia Vị & Đồ Khô'), ('do_uong', 'Đồ Uống (Chai/Lon)'), ('khac', 'Khác')], default='khac', max_length=50, verbose_name='Danh mục')),
                ('don_vi_tinh', models.CharField(default='Kg', max_length=50)),
                ('ton_kho', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tồn kho hiện tại')),
                ('muc_canh_bao', models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Mức tồn tối thiểu')),
                ('don_gia_trung_binh', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Đơn giá TB')),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ncc', models.CharField(max_length=255, verbose_name='Tên Nhà Cung Cấp')),
                ('nguoi_lien_he', models.CharField(blank=True, max_length=255, null=True)),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang hợp tác')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True)),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cong_no', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Công nợ (VNĐ)')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuKho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('loai_phieu', models.CharField(choices=[('nhap', 'Phiếu Nhập Kho'), ('xuat', 'Phiếu Xuất Kho')], default='nhap', max_length=10)),
                ('ngay_thuc_hien', models.DateTimeField(default=django.utils.timezone.now)),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('da_thanh_toan', models.BooleanField(default=True)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_thuc_hien', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nha_cung_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietPhieuKho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số lượng')),
                ('don_gia', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Đơn giá (chỉ dùng cho Nhập)')),
                ('thanh_tien', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True)),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nguyenlieu')),
                ('phieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='inventory.phieukho')),
            ],
        ),
    ]
