# Generated by Django 6.0.3 on 2026-03-25 15:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMucNguyenLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=255, verbose_name='Tên danh mục (Hải sản, Rau củ, Đồ uống...)')),
                ('ghi_chu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ncc', models.CharField(max_length=255, verbose_name='Tên Nhà Cung Cấp')),
                ('nguoi_lien_he', models.CharField(blank=True, max_length=255, null=True, verbose_name='Người liên hệ')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang hợp tác')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=20, null=True)),
                ('dia_chi', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cong_no', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Công nợ (VNĐ)')),
            ],
        ),
        migrations.CreateModel(
            name='NguyenLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nl', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã NL')),
                ('ten_nguyen_lieu', models.CharField(max_length=255, verbose_name='Tên Nguyên liệu/Mặt hàng')),
                ('don_vi_tinh', models.CharField(default='Kg', max_length=50, verbose_name='Đơn vị tính (Kg, Lít, Thùng...)')),
                ('ton_kho', models.FloatField(default=0.0, verbose_name='Tồn kho hiện tại')),
                ('muc_canh_bao', models.FloatField(default=10.0, verbose_name='Mức tồn tối thiểu (Cảnh báo đỏ)')),
                ('don_gia_trung_binh', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Đơn giá TB')),
                ('danh_muc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.danhmucnguyenlieu', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã Phiếu Nhập')),
                ('ngay_nhap', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Ngày nhập kho')),
                ('tong_tien_nhap', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền')),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_nhap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên Kho')),
                ('nha_cung_cap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nhacungcap', verbose_name='Nhà cung cấp')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietNhapKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.FloatField(verbose_name='Số lượng nhập')),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá nhập')),
                ('thanh_tien', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True)),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nguyenlieu')),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='inventory.phieunhapkho')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã Phiếu Xuất')),
                ('ly_do_xuat', models.CharField(default='Xuất cho Bếp chính', max_length=255, verbose_name='Lý do xuất')),
                ('ngay_xuat', models.DateTimeField(default=django.utils.timezone.now)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('nguoi_xuat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người xuất')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietXuatKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_xuat', models.FloatField(verbose_name='Số lượng xuất')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú món')),
                ('nguyen_lieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nguyenlieu')),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='inventory.phieuxuatkho')),
            ],
        ),
    ]
