# Generated by Django 6.0.3 on 2026-03-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguyenlieu',
            name='muc_canh_bao',
            field=models.FloatField(default=10.0, verbose_name='Mức tồn tối thiểu'),
        ),
    ]
