# Generated by Django 6.0.3 on 2026-03-27 14:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_alter_nguyenlieu_muc_canh_bao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietnhapkho',
            name='so_luong',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số lượng nhập'),
        ),
        migrations.AlterField(
            model_name='chitietxuatkho',
            name='ghi_chu',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='chitietxuatkho',
            name='so_luong_xuat',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số lượng xuất'),
        ),
        migrations.AlterField(
            model_name='danhmucnguyenlieu',
            name='ten_danh_muc',
            field=models.CharField(max_length=255, verbose_name='Tên danh mục'),
        ),
        migrations.AlterField(
            model_name='nguyenlieu',
            name='don_vi_tinh',
            field=models.CharField(default='Kg', max_length=50),
        ),
        migrations.AlterField(
            model_name='nguyenlieu',
            name='muc_canh_bao',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=10, verbose_name='Mức tồn tối thiểu'),
        ),
        migrations.AlterField(
            model_name='nguyenlieu',
            name='ten_nguyen_lieu',
            field=models.CharField(max_length=255, verbose_name='Tên Nguyên liệu'),
        ),
        migrations.AlterField(
            model_name='nguyenlieu',
            name='ton_kho',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Tồn kho hiện tại'),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='nguoi_lien_he',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='phieunhapkho',
            name='ma_phieu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phieunhapkho',
            name='ngay_nhap',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='phieunhapkho',
            name='nguoi_nhap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='phieunhapkho',
            name='nha_cung_cap',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nhacungcap'),
        ),
        migrations.AlterField(
            model_name='phieunhapkho',
            name='tong_tien_nhap',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='phieuxuatkho',
            name='ly_do_xuat',
            field=models.CharField(default='Xuất cho Bếp chính', max_length=255),
        ),
        migrations.AlterField(
            model_name='phieuxuatkho',
            name='ma_phieu',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='phieuxuatkho',
            name='nguoi_xuat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
