# Generated by Django 6.0.3 on 2026-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_chitietnhapkho_so_luong_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieunhapkho',
            name='da_thanh_toan',
            field=models.BooleanField(default=True),
        ),
    ]
