# Generated by Django 6.0.3 on 2026-03-25 15:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuVuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khu_vuc', models.CharField(max_length=100, verbose_name='Khu vực (Tầng 1/VIP)')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
        ),
        migrations.CreateModel(
            name='BanAn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ban', models.CharField(max_length=50, verbose_name='Tên/Số bàn')),
                ('so_ghe', models.IntegerField(default=4, verbose_name='Số ghế')),
                ('trang_thai', models.CharField(choices=[('trong', 'Bàn Trống'), ('dang_an', 'Đang Phục Vụ'), ('da_dat', 'Đã Đặt Trước'), ('cho_thanh_toan', 'Chờ Thanh Toán')], default='trong', max_length=20)),
                ('khu_vuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_ban', to='reception.khuvuc')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuDatBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_den', models.DateTimeField(verbose_name='Thời gian khách đến')),
                ('so_nguoi', models.IntegerField(default=1)),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('hoan_thanh', 'Đã check-in'), ('huy', 'Đã hủy')], default='cho_xac_nhan', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Lúc đặt')),
                ('ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_dat_ban', to='reception.banan')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_dat_ban', to='customers.khachhang')),
            ],
        ),
        migrations.CreateModel(
            name='PhienSuDungBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_vao', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Giờ Check-in')),
                ('thoi_gian_ra', models.DateTimeField(blank=True, null=True, verbose_name='Giờ Check-out')),
                ('so_khach_thuc_te', models.IntegerField(default=1)),
                ('trang_thai', models.CharField(choices=[('dang_phuc_vu', 'Đang phục vụ'), ('da_thanh_toan', 'Đã thanh toán'), ('huy', 'Đã hủy (Khách bỏ về)')], default='dang_phuc_vu', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cac_phien', to='reception.banan')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.khachhang')),
                ('phieu_dat', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.phieudatban')),
            ],
        ),
    ]
