# Generated by Django 5.2.10 on 2026-05-23 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BanAn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ban', models.CharField(max_length=50, verbose_name='Tên/Số bàn')),
                ('so_ghe', models.IntegerField(default=4, verbose_name='Số ghế')),
                ('khu_vuc', models.CharField(choices=[('Tang_1', 'Tầng 1 (Sảnh chung)'), ('VIP', 'Khu VIP (Phòng riêng)'), ('Ngoai_troi', 'Khu Ngoài Trời')], default='Tang_1', max_length=20, verbose_name='Khu vực')),
                ('trang_thai', models.CharField(choices=[('trong', 'Bàn Trống'), ('dang_an', 'Đang Phục Vụ'), ('da_dat', 'Đã Đặt Trước'), ('cho_thanh_toan', 'Chờ Thanh Toán')], default='trong', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PhieuDatBan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thoi_gian_den', models.DateTimeField(verbose_name='Thời gian khách đến')),
                ('so_nguoi', models.IntegerField(default=1, verbose_name='Số người lớn')),
                ('so_tre_em', models.IntegerField(default=0, verbose_name='Số trẻ em')),
                ('trang_thai', models.CharField(choices=[('cho_xac_nhan', 'Chờ xác nhận'), ('da_xac_nhan', 'Đã xác nhận'), ('hoan_thanh', 'Đã check-in'), ('huy', 'Đã hủy')], default='cho_xac_nhan', max_length=20)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('thoi_gian_tao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Lúc đặt')),
                ('ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_dat_ban', to='reception.banan')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lich_su_dat_ban', to='customers.khachhang')),
            ],
        ),
    ]
