# Generated by Django 6.0.3 on 2026-03-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieudatban',
            name='so_tre_em',
            field=models.IntegerField(default=0, verbose_name='Số trẻ em'),
        ),
        migrations.AlterField(
            model_name='phieudatban',
            name='so_nguoi',
            field=models.IntegerField(default=1, verbose_name='Số người lớn'),
        ),
    ]
