# Generated by Django 5.2.10 on 2026-05-23 23:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuVuc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_khu_vuc', models.CharField(max_length=100, verbose_name='Tên Khu Vực')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả')),
            ],
        ),
        migrations.AlterField(
            model_name='banan',
            name='khu_vuc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.khuvuc', verbose_name='Khu vực'),
        ),
    ]
