# Generated by Django 6.0.3 on 2026-03-25 15:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('menu', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hoa_don', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Mã Hóa Đơn')),
                ('thoi_gian_vao', models.DateTimeField(auto_now_add=True, verbose_name='Giờ khách vào')),
                ('thoi_gian_ra', models.DateTimeField(blank=True, null=True, verbose_name='Giờ in bill/Ra')),
                ('so_khach', models.IntegerField(default=1, verbose_name='Số lượng khách')),
                ('tong_tien_hang', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Tổng tiền hàng')),
                ('chiet_khau', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Giảm giá / Voucher')),
                ('vat_phu_thu', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='VAT & Phụ thu khác')),
                ('khach_can_tra', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Khách cần trả')),
                ('ghi_chu', models.TextField(blank=True, null=True, verbose_name='Ghi chú hóa đơn')),
                ('trang_thai', models.CharField(choices=[('dang_phuc_vu', 'Đang phục vụ'), ('da_thanh_toan', 'Đã thanh toán'), ('da_huy', 'Đã hủy')], default='dang_phuc_vu', max_length=20)),
                ('ban_an', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reception.banan', verbose_name='Bàn ăn')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.khachhang', verbose_name='Khách hàng (Thành viên)')),
                ('nhan_vien', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Thu ngân / Nhân viên')),
            ],
        ),
        migrations.CreateModel(
            name='ChiTietHoaDon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon_luu_tru', models.CharField(max_length=255, verbose_name='Tên món (Snapshot)')),
                ('don_gia_luu_tru', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Đơn giá (Snapshot)')),
                ('so_luong', models.IntegerField(default=1, verbose_name='Số lượng')),
                ('thanh_tien', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Thành tiền')),
                ('thoi_gian_order', models.DateTimeField(auto_now_add=True)),
                ('ghi_chu_bep', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú bếp (VD: Ít đá, cay...)')),
                ('do_uong', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.douongdichvu')),
                ('goi_buffet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.goibuffet')),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='pos.hoadon', verbose_name='Thuộc Hóa Đơn')),
            ],
        ),
        migrations.CreateModel(
            name='ThanhToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phuong_thuc', models.CharField(choices=[('tien_mat', 'Tiền mặt (Cash)'), ('chuyen_khoan', 'Chuyển khoản (Bank Transfer)'), ('quet_the', 'Quẹt thẻ (POS / Credit)')], default='tien_mat', max_length=20, verbose_name='Phương thức TT')),
                ('so_tien_thu', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Số tiền đã thu')),
                ('thoi_gian_thu', models.DateTimeField(auto_now_add=True, verbose_name='Thời gian giao dịch')),
                ('ma_giao_dich_ngan_hang', models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch (Nội dung chuyển khoản)')),
                ('hoa_don', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanh_toan', to='pos.hoadon', verbose_name='Thuộc Hóa Đơn')),
                ('nhan_vien_thu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người thu tiền')),
            ],
        ),
    ]
