# Generated by Django 6.0.3 on 2026-03-25 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
        ('reception', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='phien_su_dung',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hoa_don', to='reception.phiensudungban'),
        ),
        migrations.AlterField(
            model_name='chitiethoadon',
            name='ghi_chu_bep',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú bếp'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='nhan_vien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Thu ngân'),
        ),
        migrations.AlterField(
            model_name='thanhtoan',
            name='ma_giao_dich_ngan_hang',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Mã giao dịch'),
        ),
    ]
