# Generated by Django 6.0.3 on 2026-03-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('pos', '0002_hoadon_phien_su_dung_alter_chitiethoadon_ghi_chu_bep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chitiethoadon',
            name='ghi_chu_bep',
        ),
        migrations.AddField(
            model_name='chitiethoadon',
            name='ghi_chu',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ghi chú (Ít đá, không cay...)'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='khach_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.khachhang', verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='trang_thai',
            field=models.CharField(choices=[('dang_phuc_vu', 'Đang phục vụ'), ('cho_thanh_toan', 'Chờ thanh toán'), ('da_thanh_toan', 'Đã thanh toán'), ('da_huy', 'Đã hủy')], default='dang_phuc_vu', max_length=20),
        ),
    ]
