# Generated by Django 6.0.3 on 2026-05-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_remove_chitiethoadon_ghi_chu_bep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hoadon',
            name='ma_voucher',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='hoadon',
            name='tien_giam_voucher',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=12),
        ),
    ]
