# Generated by Django 5.2.10 on 2026-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('so_dien_thoai', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('diem_tich_luy', models.IntegerField(default=0, verbose_name='Điểm thành viên')),
                ('is_active', models.BooleanField(default=True, verbose_name='Trạng thái (Khóa/Mở)')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_code', models.CharField(max_length=50, unique=True, verbose_name='Mã Code')),
                ('muc_giam', models.CharField(max_length=50, verbose_name='Mức giảm (vd: 15% hoặc 200000)')),
                ('dieu_kien_toi_thieu', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Điều kiện hóa đơn')),
                ('ngay_het_han', models.DateField(verbose_name='Ngày hết hạn')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Trạng thái kích hoạt')),
                ('ai_de_xuat', models.BooleanField(default=False, verbose_name='Do AI đề xuất')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
