# Generated by Django 6.0.3 on 2026-03-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=255, verbose_name='Tên khách hàng')),
                ('so_dien_thoai', models.CharField(max_length=20, unique=True, verbose_name='Số điện thoại')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('diem_tich_luy', models.IntegerField(default=0, verbose_name='Điểm thành viên')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Ngày tạo')),
            ],
        ),
    ]
