# Generated by Django 6.0.3 on 2026-05-17 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_code', models.CharField(max_length=50, unique=True, verbose_name='Mã Code')),
                ('muc_giam', models.CharField(max_length=50, verbose_name='Mức giảm (vd: 15% hoặc 200000)')),
                ('dieu_kien_toi_thieu', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='Điều kiện hóa đơn')),
                ('ngay_het_han', models.DateField(verbose_name='Ngày hết hạn')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Trạng thái kích hoạt')),
                ('ai_de_xuat', models.BooleanField(default=False, verbose_name='Do AI đề xuất')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='khachhang',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái (Khóa/Mở)'),
        ),
    ]
