# Generated by Django 5.2.10 on 2026-05-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThucDon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=255, verbose_name='Tên Món / Gói')),
                ('loai_mon', models.CharField(choices=[('goi_buffet', 'Gói Buffet'), ('do_uong', 'Đồ Uống'), ('dich_vu', 'Dịch vụ Phụ thu')], default='do_uong', max_length=20)),
                ('danh_muc', models.CharField(choices=[('buffet', 'Buffet'), ('nuoc_ngot', 'Nước Ngọt'), ('bia_ruou', 'Bia & Rượu'), ('hai_san', 'Hải Sản Gọi Thêm'), ('phu_thu', 'Phụ Thu Dịch Vụ')], default='nuoc_ngot', max_length=50)),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú')),
                ('ma_sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã SKU')),
                ('gia_ban', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá Bán (VNĐ)')),
                ('gia_von', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Giá Vốn')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='menu/')),
                ('gio_bat_dau', models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Hiển thị trên POS')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
