# Generated by Django 6.0.3 on 2026-03-25 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_danh_muc', models.CharField(max_length=255, unique=True, verbose_name='Tên Danh Mục')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả ghi chú')),
                ('icon', models.CharField(default='bi-cup-straw', max_length=50, verbose_name='Icon hiển thị')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Hiển thị trên POS')),
            ],
        ),
        migrations.CreateModel(
            name='GoiBuffet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_goi', models.CharField(max_length=255, verbose_name='Tên Gói Buffet')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả / Ghi chú')),
                ('gia_ban', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá Bán (VNĐ)')),
                ('gio_bat_dau', models.TimeField(blank=True, null=True, verbose_name='Giờ bắt đầu')),
                ('gio_ket_thuc', models.TimeField(blank=True, null=True, verbose_name='Giờ kết thúc')),
                ('ngay_ap_dung', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ngày áp dụng (T2-CN)')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang áp dụng')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NgayLe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_ngay_le', models.CharField(max_length=255, verbose_name='Tên Ngày Lễ')),
                ('ngay', models.DateField(verbose_name='Ngày Lễ')),
            ],
        ),
        migrations.CreateModel(
            name='QuayLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_quay', models.CharField(max_length=50, unique=True, verbose_name='Mã Quầy')),
                ('ten_quay', models.CharField(max_length=255, verbose_name='Tên Quầy Line')),
                ('mo_ta', models.CharField(blank=True, max_length=500, null=True, verbose_name='Mô tả / Vị trí')),
                ('loai_icon', models.CharField(choices=[('bi-fire', 'Lửa (Đồ nướng)'), ('bi-water', 'Nước (Hải sản)'), ('bi-snow', 'Bông tuyết (Đồ sống/Lạnh)'), ('bi-cup-hot-fill', 'Nồi nóng (Lẩu/Món nóng)'), ('bi-egg-fried', 'Trứng chiên (Chiên/Xào)'), ('bi-cake2-fill', 'Bánh (Tráng miệng)'), ('bi-cup-straw', 'Cốc nước (Đồ uống)'), ('bi-shop', 'Chợ quê (Món Việt)')], default='bi-shop', max_length=50)),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang hoạt động')),
            ],
        ),
        migrations.CreateModel(
            name='DoUongDichVu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=255, verbose_name='Tên Món / Phụ thu')),
                ('ma_sku', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã SKU')),
                ('gia_ban', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá Bán / Phí')),
                ('gia_von', models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Giá Vốn (Cost)')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='beverages/')),
                ('con_hang', models.BooleanField(default=True, verbose_name='Còn hàng')),
                ('hien_thi_pos', models.BooleanField(default=True, verbose_name='Hiển thị POS')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('danh_muc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_sach_item', to='menu.danhmuc', verbose_name='Danh mục')),
            ],
        ),
        migrations.CreateModel(
            name='MonBuffet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_mon', models.CharField(max_length=255, verbose_name='Tên Món Ăn')),
                ('ma_mon', models.CharField(blank=True, max_length=50, null=True, verbose_name='Mã Món (SKU)')),
                ('phan_loai', models.CharField(choices=[('seafood', 'Hải sản'), ('sushi', 'Sushi & Sashimi'), ('hotdish', 'Món nóng (Hot dish)'), ('bbq', 'Nướng & BBQ'), ('dimsum', 'Dimsum & Hấp'), ('vietnamese', 'Món Việt / Chợ Quê'), ('salad', 'Salad & Khai vị'), ('dessert', 'Tráng miệng'), ('drink', 'Nước uống')], default='seafood', max_length=50)),
                ('gia_von_uoc_tinh', models.DecimalField(decimal_places=0, default=0, max_digits=10, verbose_name='Giá Vốn Ước Tính')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Đang phục vụ')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='buffet_dishes/')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('vi_tri_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_sach_mon', to='menu.quayline', verbose_name='Thuộc Quầy Line')),
            ],
        ),
    ]
