# Generated by Django 6.0.3 on 2026-03-27 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='danhmuc',
            name='icon',
            field=models.CharField(default='bi-cup-straw', max_length=50),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='mo_ta',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='danhmuc',
            name='trang_thai',
            field=models.BooleanField(default=True, verbose_name='Hiển thị POS'),
        ),
        migrations.AlterField(
            model_name='douongdichvu',
            name='danh_muc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_sach_item', to='menu.danhmuc'),
        ),
        migrations.AlterField(
            model_name='douongdichvu',
            name='gia_von',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=10, null=True, verbose_name='Giá Vốn'),
        ),
        migrations.AlterField(
            model_name='monbuffet',
            name='phan_loai',
            field=models.CharField(choices=[('seafood', 'Hải sản'), ('sushi', 'Sushi & Sashimi'), ('hotdish', 'Món nóng'), ('bbq', 'Nướng & BBQ'), ('dimsum', 'Dimsum & Hấp'), ('vietnamese', 'Món Việt'), ('salad', 'Salad & Khai vị'), ('dessert', 'Tráng miệng'), ('drink', 'Nước uống')], default='seafood', max_length=50),
        ),
        migrations.AlterField(
            model_name='monbuffet',
            name='vi_tri_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='danh_sach_mon', to='menu.quayline'),
        ),
        migrations.AlterField(
            model_name='quayline',
            name='mo_ta',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
