# Generated by Django 5.2.10 on 2026-06-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thucdon',
            name='ap_dung_cn',
            field=models.BooleanField(default=True, verbose_name='Chủ Nhật'),
        ),
        migrations.AddField(
            model_name='thucdon',
            name='ap_dung_t2',
            field=models.BooleanField(default=True, verbose_name='Thứ 2'),
        ),
        migrations.AddField(
            model_name='thucdon',
            name='ap_dung_t3',
            field=models.BooleanField(default=True, verbose_name='Thứ 3'),
        ),
        migrations.AddField(
            model_name='thucdon',
            name='ap_dung_t4',
            field=models.BooleanField(default=True, verbose_name='Thứ 4'),
        ),
        migrations.AddField(
            model_name='thucdon',
            name='ap_dung_t5',
            field=models.BooleanField(default=True, verbose_name='Thứ 5'),
        ),
        migrations.AddField(
            model_name='thucdon',
            name='ap_dung_t6',
            field=models.BooleanField(default=True, verbose_name='Thứ 6'),
        ),
        migrations.AddField(
            model_name='thucdon',
            name='ap_dung_t7',
            field=models.BooleanField(default=True, verbose_name='Thứ 7'),
        ),
    ]
