# Generated by Django 6.0.3 on 2026-05-20 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_danhmuc_icon_alter_danhmuc_mo_ta_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonBuffet',
        ),
        migrations.DeleteModel(
            name='QuayLine',
        ),
    ]
